# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.1
  ansible-playbook: orbss/ansible-playbook@0.0.5

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  execute-cfn:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID	
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: deploy CloudFormation
          command: |
            set -x
            aws cloudformation deploy --template-file cloudformation/sample.yaml --stack-name sample-stack
  execute-ansible:
    executor: ansible-playbook/default
    steps:
      - checkout
      - ansible-playbook/install:
          version: 2.10.7


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  devops-workflow:
    jobs:
      - execute-cfn
      - execute-ansible:
          requires:
            - execute-cfn
